SF-Digital/design-system

packages/eslint-config/CHANGELOG.md
packages/eslint-config/package.json
packages/react/.turbo/turbo-build.log
packages/react/CHANGELOG.md
packages/react/dist/index.d.mts
packages/react/dist/index.d.ts
packages/react/package.json
packages/tokens/.turbo/turbo-build.log
packages/tokens/CHANGELOG.md
packages/tokens/package.json
packages/ts-config/CHANGELOG.md
packages/ts-config/package.json

## Description
Make a minor bump to the versions, to add **Select** component to the `@sf-digital-ui/react` package.
- [] 📜 README.md
- [] 📕 Storybook

Bump Version - Add Select Component

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/deploy-docs.yml
.github/workflows/release.yml

- [] 🍕 Feature 
- [] 🧑‍💻 Code Refactor
- [] 🔥 Performance Improvements
- [] 🤖 Chore
- [] 🔁 CI
## Description
- [] 📜 README.md
- [] 📕 Storybook
- [] 🙅‍♂️ No documentation needed

fix: gh actions

---

package-lock.json
packages/docs/src/stories/Toggle.stories.tsx
packages/react/.turbo/turbo-build.log
packages/react/dist/index.d.mts
packages/react/dist/index.d.ts
packages/react/dist/index.js
packages/react/dist/index.mjs
packages/react/package.json
packages/react/src/components/Avatar/Root/index.tsx
packages/react/src/components/Button/ButtonRoot/index.tsx
packages/react/src/components/Checkbox/CheckboxRoot/index.tsx
packages/react/src/components/TextInput/Root/index.tsx
packages/react/src/components/Toggle/Control/index.tsx
packages/react/src/components/Toggle/Root/index.tsx
packages/tokens/.turbo/turbo-build.log

[Ticket 1292](https://dev.azure.com/stonehagefleming/SF-Digital/_sprints/taskboard/SF-Digital%20Team/SF-Digital/Sprint%202?workitem=1292)
[Ticket 1293](https://dev.azure.com/stonehagefleming/SF-Digital/_sprints/taskboard/SF-Digital%20Team/SF-Digital/Sprint%202?workitem=1293)
**Default Values**: each component exported should have default values for all the different characteristics that component is reliant on, to enhance developer experience.
**Switch - Radix UI (Refactor)**: The previous component I built was built using the [Toggle](https://www.radix-ui.com/primitives/docs/components/toggle) component from Radix UI, with some pretty serious CSS lol, but I then found out that Radix offer a …

Switch Component & Default Values

---

packages/react/.turbo/turbo-build.log
packages/react/dist/index.d.mts
packages/react/dist/index.d.ts
packages/react/dist/index.js
packages/react/dist/index.mjs
packages/react/src/components/Box/index.tsx
packages/react/src/components/Checkbox/CheckboxRoot/index.tsx
packages/react/src/components/TextInput/Control/index.tsx
packages/react/src/components/TextInput/Root/index.tsx
packages/tokens/.turbo/turbo-build.log

- Fixed `Input.Root` width removed
- `Input.Control` is now a forwardRef, can be used with React Hook Form
- New Component: `Box`

fix: input width

---

packages/react/src/components/Heading/index.tsx

- Set the twMerge to `false` so that tailwind props sent in className will be applied to component

Heading Style Merge

---

packages/docs/src/stories/Button.stories.tsx
packages/react/.turbo/turbo-build.log
packages/react/CHANGELOG.md
packages/react/dist/index.d.mts
packages/react/dist/index.d.ts
packages/react/dist/index.js
packages/react/dist/index.mjs
packages/react/package.json
packages/react/src/components/Button/ButtonRoot/index.tsx
packages/react/src/components/Tabs/Trigger/index.tsx
packages/tokens/.turbo/turbo-build.log

- New `Button` variant: **gray**
- Fix to `Tab` to only have an  underline if **state="active"**

Button Variant: Gray + Tabs Line Fix

---

package-lock.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/react/src/components/Select/Item/index.tsx

Just changing the colour of the hover.

fix: select hover color

---

packages/docs/src/stories/Tooltip.stories.tsx
packages/react/CHANGELOG.md
packages/react/package.json

To deploy the new select tweaks.

fix: tooltip and select fixes

---

package-lock.json

cbummmmmmm

---

.vscode/settings.json
packages/eslint-config/CHANGELOG.md
packages/eslint-config/package.json
packages/react-native/CHANGELOG.md
packages/react-native/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/tokens/CHANGELOG.md
packages/tokens/package.json
packages/ts-config/CHANGELOG.md
packages/ts-config/package.json

chore: update packages

---

apps/react-native-doc/.yalc/@sf-digital-ui/react-native/package.json
package-lock.json
packages/react-native/package.json

fix: update dev script to use chokidar for file watching

---

packages/react-native/src/components/Button/Root/index.tsx

chore: add ring

---

packages/docs/src/stories/Tabs.stories.tsx
packages/react/dist/index.d.mts
packages/react/dist/index.d.ts
packages/react/dist/index.js
packages/react/dist/index.mjs
packages/react/src/components/Tabs/Root/index.tsx
packages/react/src/components/Tabs/Trigger/index.tsx

- New variants: `underline-filled` and `panel`
- **Underline** has colors `sf-green` and `succession-blue` available
- **Panel** has colors `neutral` available
- New color: `neutral`
- Available in `solid`, and `panel` variants
- `Tabs.Root` has a new `hasBackground` prop, that will give a container to the items

Refactor: Tabs Component

---

apps/react-native-doc/src/app/(drawer)/button.tsx
apps/react-native-doc/src/app/(drawer)/radiogroup.tsx
apps/react-native-doc/src/app/(drawer)/tabs.tsx
packages/docs/src/stories/Tabs.stories.tsx
packages/react-native/src/components/Tabs/Content/index.tsx
packages/react-native/src/components/Tabs/List/index.tsx
packages/react-native/src/components/Tabs/Root/index.tsx
packages/react-native/src/components/Tabs/Trigger/index.tsx
packages/react-native/src/components/Tabs/TriggerText/index.tsx
packages/react-native/src/components/Tabs/index.tsx
packages/react-native/src/index.tsx

[Tabs Devops Ticket](https://dev.azure.com/StonehageFleming/SF-Digital/_sprints/taskboard/SF-Digital%20Team/SF-Digital/Sprint%2023?workitem=6884)
`import { Tabs } from '@sf-digital-ui/react-native'`
Tabs is a composition of the following components:
`Tabs.Root` - Contains all the tab component parts
`Tabs.List` - Contains the triggers aligned along the edge of active content
`Tabs.Trigger` - The clickable element that activates its assocaited content
`Tabs.TriggerText` - The text content of the trigger
`Tabs.Content` - The content that is activated by its associated trigger

Tabs Component

---

apps/react-native-doc/routes.ts
apps/react-native-doc/src/app/(drawer)/switch.tsx
packages/react-native/src/components/Switch/index.tsx
packages/react-native/src/index.tsx

[Devops Ticket](https://dev.azure.com/StonehageFleming/SF-Digital/_sprints/taskboard/SF-Digital%20Team/SF-Digital/Sprint%2023?workitem=6892)
`import { Switch } from '@sf-digital-ui/react-native`

Switch Component

---

apps/react-native-doc/routes.ts
apps/react-native-doc/src/app/(drawer)/checkbox.tsx
apps/react-native-doc/src/app/(drawer)/select.tsx
packages/react-native/src/components/Select/Content/index.tsx
packages/react-native/src/components/Select/Item/index.tsx
packages/react-native/src/components/Select/ItemText/index.tsx
packages/react-native/src/components/Select/Root/index.tsx
packages/react-native/src/components/Select/Trigger/index.tsx
packages/react-native/src/components/Select/Value/index.tsx
packages/react-native/src/components/Select/Viewport/index.tsx
packages/react-native/src/components/Select/index.tsx
packages/react-native/src/index.tsx

[Devops Ticket](https://dev.azure.com/StonehageFleming/SF-Digital/_sprints/taskboard/SF-Digital%20Team/SF-Digital/Sprint%2023?workitem=6895)
`import { Select } from '@sf-digital-ui/react-native`

Select Component

---

packages/react-native/CHANGELOG.md
packages/react-native/package.json
packages/react/CHANGELOG.md
packages/react/package.json
packages/tokens/CHANGELOG.md
packages/tokens/package.json

### Release
- `@sf-digital-ui/react-native` @ **2.0.0**
- Patches to `@sf-digital-ui/react` and `@sf-digital-ui/tokens`

[RELEASE] React Native Components

---

README.md
packages/react-native/package.json

fix: release script for react native

---

apps/react-native-doc/src/app/(drawer)/tabs.tsx

Flex wrap around the Tabs list

[FIX] Tabs Documentation

---

.gitignore
apps/react-native-doc/jest.config.js
apps/react-native-doc/jest.setup.js
apps/react-native-doc/package-lock.json
apps/react-native-doc/package.json
apps/react-native-doc/src/tests/button.test.tsx
apps/react-native-doc/src/utils/test-utils.tsx
package-lock.json

Basic configuration for tests and an example test for the button component.
CD into the /react-native-docs file and then run 'npm run test'

feat: button component test

---

packages/react-native/CHANGELOG.md
packages/react-native/package.json
packages/react-native/src/components/Button/Text/index.tsx
packages/react-native/src/components/Checkbox/Root/index.tsx
packages/react-native/src/components/Modal/Content/index.tsx
packages/react-native/src/components/Modal/Description/index.tsx
packages/react-native/src/components/Modal/Overlay/index.tsx
packages/react-native/src/components/Modal/Title/index.tsx
packages/react-native/src/components/RadioGroup/Item/index.tsx
packages/react-native/src/components/Select/Content/index.tsx
packages/react-native/src/components/TextArea/index.tsx

- Merge styles fix
- New: `Modal` component
- TextInput pattern composed

React Native @ 2.1.0 release

---

.github/workflows/release.yml
apps/react-native-doc/src/tests/radiogroup.test.tsx
package.json
packages/react-native/src/components/RadioGroup/Item/index.tsx
packages/react-native/src/components/RadioGroup/Root/index.tsx

- Unit tests covering Radigroup
- Add unit testing script to pipelines

RadioGroup [Unit Tests]

---

apps/react-native-doc/src/tests/tabs.test.tsx
packages/react-native/src/components/Tabs/TriggerText/index.tsx

Tabs [Unit Test]

---

.github/workflows/release.yml
apps/react-native-doc/package-lock.json
package-lock.json
package.json

release pipeline fix

---

.github/workflows/release.yml

fix: test pipeline installl jest

---

apps/react-native-doc/jest.config.js
apps/react-native-doc/jest.setup.js
apps/react-native-doc/package.json

fix: unit tests on ci pipeline

---

.github/workflows/release.yml

chore: chore

---

apps/react-native-doc/jest.config.js
apps/react-native-doc/package.json

fix: pipeline test

---

.gitignore
apps/react-native-doc/package-lock.json
apps/react-native-doc/package.json

fix: pipeline again again again

---

.github/workflows/release.yml
.gitignore
apps/react-native-doc/jest.config.js
apps/react-native-doc/jest.setup.js
apps/react-native-doc/package-lock.json
apps/react-native-doc/package.json

fix: pipeline again

---

apps/react-native-doc/src/tests/heading.test.tsx
apps/react-native-doc/src/utils/test-utils.tsx

Heading component unit test
Test for Heading component

add heading component tests and mock font sizes

---

apps/react-native-doc/jest.config.js
apps/react-native-doc/src/tests/checkbox.test.tsx

[Ticket 8225](https://dev.azure.com/stonehagefleming/SF-Digital/_sprints/taskboard/SF-Digital%20Team/SF-Digital/Sprint%2025?workitem=8225)
- Unit Testing coverage for Checkbox component

Checkbox [Unit Test]

---

.github/workflows/release.yml
apps/react-native-doc/jest.setup.js
apps/react-native-doc/src/tests/select.test.tsx

[Ticket 8230](https://dev.azure.com/stonehagefleming/SF-Digital/_sprints/taskboard/SF-Digital%20Team/SF-Digital/Sprint%2025?workitem=8230)
Select Unit Tests

Select Component [Unit Testing]

---

apps/react-native-doc/src/tests/modal.test.tsx

[Ticket 8227](https://dev.azure.com/stonehagefleming/SF-Digital/_sprints/taskboard/SF-Digital%20Team/SF-Digital/Sprint%2025?workitem=8227)
Modal Component Unit Testing

Modal Component [Unit Test]

---

apps/react-native-doc/src/tests/textarea.test.tsx

[Ticket 8234](https://dev.azure.com/stonehagefleming/SF-Digital/_sprints/taskboard/SF-Digital%20Team/SF-Digital/Sprint%2025?workitem=8234)
Unit testing Text Area

Text Area [Unit Testing]

---

apps/react-native-doc/jest.setup.js
apps/react-native-doc/src/tests/dropdownmenu.test.tsx
packages/react-native/src/components/DropdownMenu/Content/index.tsx
packages/react-native/src/components/DropdownMenu/Trigger/index.tsx

[Ticket 8226](https://dev.azure.com/stonehagefleming/SF-Digital/_sprints/taskboard/SF-Digital%20Team/SF-Digital/Sprint%2025?workitem=8226)
Unit Tests Dropdown Menu

Dropdown Menu [Unit Test]

---

apps/react-native-doc/src/tests/avatar.test.tsx

test: add unit tests for Avatar component

---

apps/react-native-doc/src/app/(drawer)/button.tsx
packages/react-native/CHANGELOG.md
packages/react-native/package.json
packages/react-native/src/components/Button/Root/index.tsx
packages/react-native/src/components/Button/Text/index.tsx

[Ticket 8909](https://dev.azure.com/StonehageFleming/SF-Digital/_sprints/taskboard/SF-Digital%20Team/SF-Digital/Sprint%2025?workitem=8909)
- Bug Fix: Button.Text not centered in Root
- Patch Release: `@sf-digital-ui/react-native`

Patch React Native Release

---

apps/react-native-doc/src/tests/card.test.tsx

Unit test covering card component usage and usage different from default to ensure proper rendering

test: add unit tests for Card component

---

apps/react-native-doc/package-lock.json
apps/react-native-doc/src/app/(drawer)/button.tsx
packages/react-native/CHANGELOG.md
packages/react-native/package.json
packages/react-native/src/components/Button/Root/index.tsx

[Ticket 8909](https://dev.azure.com/StonehageFleming/SF-Digital/_sprints/taskboard/SF-Digital%20Team/SF-Digital/Sprint%2025?workitem=8909)
Fix button align text

Fix Button Text Align

---

packages/tokens/src/colors.ts

chore: file import

---

packages/react-native/CHANGELOG.md
packages/react-native/package.json

release: react native new package version

---

apps/react-native-doc/src/app/(drawer)/modal.tsx
apps/react-native-doc/src/tests/modal.test.tsx
packages/react-native/CHANGELOG.md
packages/react-native/package.json
packages/react-native/src/components/Modal/Root/index.tsx

Revert Modal
